version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: sh -c 
      "npm install &&
       npm run start:dev"
    depends_on:
      - mysql

  mysql:
    extends:
      file: docker-compose-base.yml
      service: mysql

  mongo:
    extends:
      file: docker-compose-base.yml
      service: mongo

volumes:
  mysqldata:
    driver: local